server.port=8084
spring.application.name=shrinkify

spring.datasource.url=jdbc:postgresql://localhost:5432/shrinkify
spring.datasource.username=postgres
spring.datasource.password=Deepak123
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
